name: BukkitPix
version: 1.0.19
main: io.github.pimentelleo.bukkitpix.BukkitPix
author: batmann4bot
api-version: 1.13
commands:
  autopix:
    description: Valida uma transacao realizada por PIX
    aliases: [ap, pix]
  autopixmenu:
    description: Abre o menu de itens disponivel para compra por PIX
    aliases: [comprarpix]